###
#
# Gitlab CI configuration file
#
###

# Prepare environment
variables:
  # Terminal settings
  TERM: dumb

# Build Composer stuff
php:
  stage: test
  image: roelofr/php-node:cli
  before_script:
    - composer install --dev --no-progress --no-suggest
  script:
    - composer test
  cache:
    paths:
      - ~/.config/composer
      - vendor/
