###
#
# Gitlab CI configuration file
#
###

# Prepare environment
variables:
  # Terminal settings
  TERM: dumb

# Build Composer stuff
php:
  stage: test
  image: roelofr/php-node:cli
  before_script:
    - composer require --no-progress --no-suggest squizlabs/php_codesniffer
  script:
    - find . -maxdepth 1 -type f -name '*.php' -print -exec php -l \{\} \;
    - ./vendor/bin/phpcs
  cache:
    paths:
      - ~/.config/composer
      - vendor/
